version: '3.0'

services:
  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - backend_nw
    volumes:
      - code_api:/code
    entrypoint: ["gunicorn", "main:app", "--workers", "4", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    expose:
      - 8000
    depends_on:
      - etl_service
      - redis


volumes:
  code:
  code_elt:
  code_api:
  pg_data:
  esdata:
  redis_data:

networks:
  backend_nw:
    driver: bridge
